### ISSUE TITLE
What's the status of this repo?

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxMaximaMaxima#1]
My current guess is that this doesn't work yet, but the goal is to get it working, correct? In such case, I'll see if I can make it all work gradually.

I would like at least wxMaxima to not require any special effort to cross-compile, so that this project would not need to treat wxMaxima as an external project, but just drop it in as a git submodule. I.e. the `wxmaxima` folder would be the location for the git submodule, and would not need an extra `CMakeLists.txt`. I imagine that adding maxima itself as a git submodule would also work at some point, but I've not looked closely.

**Comment by gunterkoenigsmann** [comment]
That would be great - even if not of the highest priority since we have Wolfgang's cross-compiled build that works like magic! The reason I tried to create this repo in a bout of hybris was that if I understood Wolfgang right he didn't object when I mentioned the standalone wxMaxima-including-maxima-and-gnuplot-and-tcl-and-everything-else and a CI in the same sentence. And since my own computer with 4 Gigabytes of RAM I therefore cannot cross-compile all of that I guessed that travis with 7 Gigabytes of RAM might have a hard time, too, which is why I thought of trying to use AppVeyor. But I only worked on this repo now and then since without a suitable windows computer to try things on even the simplest things simplify to trial-and-error.

**Comment by KubaO** [comment]
I don’t think that RAM is the worst limiting factor. Sure, for link time code generation it’d be a no-go, but in most cases we’re talking about really old software. tcl, tk, gcl could run on systems with 16-64MB of RAM, tcl/tk runs on microcontrollers with 8MB of RAM and less, today, and can be compiled on an ancient i386/66 with 32MB of RAM, on a bare bones Linux system. I have one of those beige boxes I fire up sometimes just to see what it could still do :)

But in essence all those project builds run compilers most of the time, and the real memory hog is linking. That’s why Ninja has job groups and can ensure that no other build tasks run when something heavy like linking needs all resources. It needs to be set up of course. It’s a major problem with make - there’s no support for that AFAIK. It often works “by default” if you build just one executable and linking is a meeting point, ie jobs can run either before the link (compilation etc) or after (packaging), but won’t cross that border. People have been adding unnecessary dependencies to makefiles to work around that. But it really should be supported at a lower level, and that’s where Ninja and cmake come in play. Of course in practice it takes stupid amount of time to set it up, but once it’s configured it all looks easy :)

Interestingly, I don’t do any local builds of that sort in spite of having a Windows platform. I only use it for writing code. Build issues etc I solve with notepad++ and careful planning and having desktop notifications for Travis and appVeyor build succeeds/failure. So I can say with clear conscience that I’ll do it the same way you do it, in terms of development platform. Something that can run a recent enough version of Chromium, has internet connection, and Notepad++ or a similar editor is all I use for cmake and shell scripts. It requires a fresh mind for sure. 

I usually write multiple approaches, push them separately, and then see what clears another hurdle on the racetrack.

**Comment by daute** [comment]
A working repository, which shows, how the crosscompiling procedure for a Windows installer for Maxima works with the Github CI is available here: <https://github.com/daute/maxima-crosscompilation>

(Compiling Maxima has not much to do with the wxMaxima project).

And a repository, which shows how to crosscompile a wxMaxima (only) Windows installer is here:
<https://github.com/wxMaxima-developers/Crosscompiled-Windows-installer>.

Closing this issue.
Best regards, Wolfgang
